# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-20.04"
  apt_packages:
    - cmake
  tools:
    python: "mambaforge-4.10"
    rust: "1.70"

python:
  install:
    #- requirements: py-ft/docs/requirements.txt
    - method: pip
      path: ./py-ft
      
#conda:
#    environment: py-ft/docs/environment.yml