[package]
authors = ["Mitchell R. Vollger <mrvollger@gmail.com>"]
categories = ["command-line-utilities"]
description = "fiberseq toolkit in rust"
edition = "2021"
homepage = "https://mrvollger.github.io/fibertools-rs/"
keywords = ["cli", "bam"]
license = "MIT"
name = "fibertools-rs"
readme = "README.md"
repository = "https://github.com/mrvollger/fibertools-rs"
version = "0.0.7"

[[bin]]
name = "ft"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.58"
bio = "0.41.0"
bio-types = "0.12.0"
clap = {version = "3.1.6", features = ["derive"]}
colored = "2.0.0"
console = "0.15"
env_logger = "0.9.0"
gbdt = "0.1.1"
indicatif = {version = "0.17.0", features = ["rayon"]}
lazy_static = "1.4.0"
log = "0.4"
rayon = "1.5"
regex = "1.5.4"
rust-htslib = "0.39.5"
spin = "0.9.4"
tch = "0.8.0"
tempfile = "3.3.0"
torch-sys = "0.8.0"
#xgboost = "0.1.4"
