[package]
authors = ["Mitchell R. Vollger <mrvollger@gmail.com>"]
build = "build.rs"
categories = ["command-line-utilities"]
description = "Fiber-seq toolkit in rust"
edition = "2021"
homepage = "https://fiberseq.github.io/fibertools-rs/"
keywords = ["cli", "bam", "bfx"]
license = "MIT"
name = "fibertools-rs"
readme = "README.md"
repository = "https://github.com/fiberseq/fibertools-rs"
version = "0.2.3"

[[bin]]
name = "ft"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.58"
bio = "1.2.0"
#bio-types = "0.12.0"
#burn = "0.7.0"
#clap = {version = "4.0.26", features = ["derive"]}
anstyle = "1.0.0"
clap = {version = "4.3.4", features = ["cargo", "wrap_help", "color", "unstable-styles", "derive"]}
#clap-markdown = "0.1.3"
clap_complete = "4.0.6"
clap_mangen = "0.2.5"
colored = "2.0.0"
console = "0.15"
env_logger = "0.9.0"
#failure = "0.1.3"
gbdt = "0.1.1"
#git2 = "0.15"
indicatif = {version = "0.17.0", features = ["rayon"]}
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4"
ordered-float = "3.4.0"
#quote = "0.6.10"
rayon = "1.5"
regex = "1.5.4"
rust-htslib = "0.43.1"
serde = {version = "1.0.104", features = ["derive"]}
serde_json = "1.0.48"
spin = "0.9.4"
#syn = "0.15.20"
bamlift = {version = "0.1.0", path = "bamlift"}
tch = {version = "0.13.0", optional = true}
tempfile = "3.3.0"

[features]
default = ["predict"]
predict = ["dep:tch"]

# generated by 'cargo dist init'
[profile.dist]
debug = true
inherits = "release"
split-debuginfo = "packed"

#[build-dependencies]
#burn-import = "0.7.0"

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"

[profile.dev]
opt-level = 2
