name: CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Check format
        run: cargo fmt -- --check

  Linting:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Install stable toolchain
         uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
           override: true
           components: clippy

       - name: Lint with clippy
         run: cargo clippy

  Testing:
    needs: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run test
        run: |
          cargo test --no-default-features -- --test-threads=1
          cargo run --no-default-features -- -v extract --all - .test/all.bam | cut -f 1-7 | head
          cargo run --no-default-features -- -v extract --msp - .test/all.bam | cut -f 1-7 | head
          cargo run --no-default-features -- -v extract --nuc - .test/all.bam | cut -f 1-7 | head
          cargo run --no-default-features -- -v extract --m6a - .test/all.bam | cut -f 1-7 | head
          cargo run --no-default-features -- -v extract --cpg - .test/all.bam | cut -f 1-7 | head
          cargo run --no-default-features -- center .test/all.bam .test/center.bed | head
